'use client'

import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { SPECIFICATION_TYPES } from "@/lib/constants";
import { updateSpecification } from "@/lib/actions/spec-features.actions";
import { Form, FormControl, FormDescription, FormField, FormItem, FormLabel, FormMessage } from "@/components/ui/form";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Checkbox } from "@/components/ui/checkbox";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { useRouter } from "next/navigation";
import { Category } from "@/types";
import { useState, useEffect } from "react";
import { toast } from "sonner";
import {
    UpdateSpecificationWithCategoriesInput,
    updateSpecificationWithCategoriesSchema
} from "@/lib/validations/specs-features.validation";

interface UpdateSpecificationFormProps {
    specification: any; // Типизировать позже
    categories: Category[];
}

const UpdateSpecificationForm = ({ specification, categories }: UpdateSpecificationFormProps) => {
    const [serverError, setServerError] = useState<string>('');
    const router = useRouter();

    // Определяем значения по умолчанию из переданной спецификации
    const defaultValues: UpdateSpecificationWithCategoriesInput = {
        id: specification.id,
        name: specification.name,
        key: specification.key,
        description: specification.description || null,
        unit: specification.unit || null,
        type: specification.type,
        icon: specification.icon || null,
        isActive: specification.isActive,
        sortOrder: specification.sortOrder,
        categoryIds: specification.categorySpecs?.map((cs: any) => cs.categoryId) || [],
        isGlobal: specification.categorySpecs?.length === categories.filter(cat => cat.isActive).length,
    };

    const form = useForm<UpdateSpecificationWithCategoriesInput>({
        resolver: zodResolver(updateSpecificationWithCategoriesSchema),
        defaultValues,
        mode: 'onChange'
    });

    const handleNameChange = (value: string) => {
        // Генерация key только если поле key пустое или совпадает с автогенерированным
        const currentKey = form.getValues('key');
        const autoGeneratedKey = specification.name
            .toLowerCase()
            .replace(/[^a-zA-Z0-9\s]/g, '')
            .trim()
            .replace(/\s+/g, '-');

        // Обновляем key только если он был автогенерированный или пустой
        if (!currentKey || currentKey === autoGeneratedKey) {
            const generatedKey = value
                .toLowerCase()
                .replace(/[^a-zA-Z0-9\s]/g, '')
                .trim()
                .replace(/\s+/g, '-');

            form.setValue('key', generatedKey, {
                shouldValidate: true,
                shouldDirty: true
            });
        }
    };

    const handleSubmit = async (values: UpdateSpecificationWithCategoriesInput) => {
        try {
            setServerError('');
            console.log('🚀 Form submitting with values:', values);

            const res = await updateSpecification(values);
            console.log('📝 Response from server:', res);

            if (res.success) {
                toast.success(res.message || 'Спецификация успешно обновлена');
                router.push('/admin/products/specifications');
            } else {
                setServerError(res.message || 'Произошла ошибка при обновлении спецификации');
                toast.error(res.message || 'Произошла ошибка при обновлении спецификации');
            }
        } catch (error) {
            console.error('❌ Client error updating specification:', error);
            const errorMessage = 'Произошла ошибка при обновлении спецификации';
            setServerError(errorMessage);
            toast.error(errorMessage);
        }
    };

    const handleCancelForm = () => {
        router.push('/admin/products/specifications');
    };

    const isGlobal = form.watch('isGlobal');

    // Обновляем categoryIds при изменении isGlobal
    useEffect(() => {
        if (isGlobal) {
            const allActiveCategoryIds = categories.filter(cat => cat.isActive).map(cat => cat.id);
            form.setValue('categoryIds', allActiveCategoryIds, {
                shouldValidate: true,
                shouldDirty: true
            });
        }
    }, [isGlobal, categories, form]);

    return (
        <div className="mx-auto py-6">
            <div className="mb-6">
                <h1 className="text-2xl font-bold">Редактировать спецификацию</h1>
                <p className="text-muted-foreground">Обновите данные спецификации товара</p>
            </div>

            <Form {...form}>
                <form
                    onSubmit={form.handleSubmit(handleSubmit)}
                    className='space-y-8'
                    noValidate
                >
                    {/* Показываем ошибку сервера */}
                    {serverError && (
                        <div className="p-4 mb-4 text-sm text-red-800 rounded-lg bg-red-50 border border-red-200">
                            {serverError}
                        </div>
                    )}

                    {/* Hidden ID field */}
                    <FormField
                        control={form.control}
                        name='id'
                        render={({ field }) => (
                            <Input type="hidden" {...field} />
                        )}
                    />

                    {/* Name */}
                    <FormField
                        control={form.control}
                        name='name'
                        render={({ field }) => (
                            <FormItem>
                                <FormLabel>
                                    Название спецификации <span className="text-red-500">*</span>
                                </FormLabel>
                                <FormControl>
                                    <Input
                                        placeholder='Введите название спецификации'
                                        {...field}
                                        onChange={(e) => {
                                            field.onChange(e);
                                            handleNameChange(e.target.value);
                                        }}
                                    />
                                </FormControl>
                                <FormDescription>
                                    Например: "Количество мест", "Температура комфорта", "Вес"
                                </FormDescription>
                                <FormMessage />
                            </FormItem>
                        )}
                    />

                    {/* Key */}
                    <FormField
                        control={form.control}
                        name='key'
                        render={({ field }) => (
                            <FormItem>
                                <FormLabel>
                                    Ключ <span className="text-red-500">*</span>
                                </FormLabel>
                                <FormControl>
                                    <Input
                                        placeholder='Ключ спецификации'
                                        {...field}
                                    />
                                </FormControl>
                                <FormDescription>
                                    Уникальный ключ для программного доступа
                                </FormDescription>
                                <FormMessage />
                            </FormItem>
                        )}
                    />

                    {/* Type and Unit */}
                    <div className='flex flex-col md:flex-row gap-6 items-start'>
                        <FormField
                            control={form.control}
                            name='type'
                            render={({ field }) => (
                                <FormItem className='flex-1'>
                                    <FormLabel>
                                        Тип <span className="text-red-500">*</span>
                                    </FormLabel>
                                    <Select onValueChange={field.onChange} value={field.value}>
                                        <FormControl>
                                            <SelectTrigger>
                                                <SelectValue placeholder="Выберите тип спецификации" />
                                            </SelectTrigger>
                                        </FormControl>
                                        <SelectContent>
                                            {SPECIFICATION_TYPES.map((type) => (
                                                <SelectItem key={type.value} value={type.value}>
                                                    {type.label}
                                                </SelectItem>
                                            ))}
                                        </SelectContent>
                                    </Select>
                                    <FormDescription>
                                        Тип данных для этой спецификации
                                    </FormDescription>
                                    <FormMessage />
                                </FormItem>
                            )}
                        />

                        <FormField
                            control={form.control}
                            name='unit'
                            render={({ field }) => (
                                <FormItem className='flex-1'>
                                    <FormLabel>
                                        Единица измерения
                                    </FormLabel>
                                    <FormControl>
                                        <Input
                                            placeholder='кг, см, °C, л'
                                            {...field}
                                            value={field.value || ''}
                                        />
                                    </FormControl>
                                    <FormDescription>
                                        Единица измерения (необязательно)
                                    </FormDescription>
                                    <FormMessage />
                                </FormItem>
                            )}
                        />
                    </div>

                    {/* Description */}
                    <FormField
                        control={form.control}
                        name='description'
                        render={({ field }) => (
                            <FormItem>
                                <FormLabel>
                                    Описание
                                </FormLabel>
                                <FormControl>
                                    <Textarea
                                        placeholder='Введите описание спецификации (необязательно)'
                                        className='resize-none min-h-24'
                                        {...field}
                                        value={field.value || ''}
                                    />
                                </FormControl>
                                <FormDescription>
                                    Подробное описание спецификации для пользователей
                                </FormDescription>
                                <FormMessage />
                            </FormItem>
                        )}
                    />

                    {/* Icon Path */}
                    <FormField
                        control={form.control}
                        name='icon'
                        render={({ field }) => (
                            <FormItem>
                                <FormLabel>
                                    Путь к иконке
                                </FormLabel>
                                <FormControl>
                                    <Input
                                        placeholder='users, thermometer, weight, ruler'
                                        {...field}
                                        value={field.value || ''}
                                    />
                                </FormControl>
                                <FormDescription>
                                    Имя иконки (Lucide, Heroicons) или путь к файлу
                                </FormDescription>
                                <FormMessage />
                            </FormItem>
                        )}
                    />

                    {/* Is Global Checkbox */}
                    <FormField
                        control={form.control}
                        name='isGlobal'
                        render={({ field }) => (
                            <FormItem className='flex flex-row items-start space-x-3 space-y-0'>
                                <FormControl>
                                    <Checkbox
                                        checked={field.value}
                                        onCheckedChange={field.onChange}
                                        aria-label="Общая для всех категорий"
                                    />
                                </FormControl>
                                <div className='space-y-1 leading-none'>
                                    <FormLabel>
                                        Общая для всех категорий
                                    </FormLabel>
                                    <FormDescription>
                                        Эта спецификация будет доступна для всех активных категорий товаров
                                    </FormDescription>
                                </div>
                                <FormMessage />
                            </FormItem>
                        )}
                    />

                    {/* Categories Selection (показываем только если не isGlobal) */}
                    {!isGlobal && (
                        <FormField
                            control={form.control}
                            name='categoryIds'
                            render={({ field }) => (
                                <FormItem>
                                    <FormLabel>
                                        Категории товаров
                                    </FormLabel>
                                    <FormDescription>
                                        Выберите категории, для которых будет доступна эта спецификация
                                    </FormDescription>
                                    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-3 mt-3">
                                        {categories.map((category) => (
                                            <div key={category.id} className="flex items-center space-x-2">
                                                <Checkbox
                                                    checked={field.value?.includes(category.id) || false}
                                                    onCheckedChange={(checked) => {
                                                        const currentValue = field.value || [];
                                                        if (checked) {
                                                            field.onChange([...currentValue, category.id]);
                                                        } else {
                                                            field.onChange(currentValue.filter(id => id !== category.id));
                                                        }
                                                    }}
                                                    aria-label={`Категория ${category.name}`}
                                                />
                                                <label className="text-sm font-medium leading-none cursor-pointer">
                                                    {category.name}
                                                </label>
                                            </div>
                                        ))}
                                    </div>
                                    <FormMessage />
                                </FormItem>
                            )}
                        />
                    )}

                    {/* Sort Order */}
                    <FormField
                        control={form.control}
                        name='sortOrder'
                        render={({ field }) => (
                            <FormItem className='max-w-xs'>
                                <FormLabel>
                                    Порядок сортировки <span className="text-red-500">*</span>
                                </FormLabel>
                                <FormControl>
                                    <Input
                                        type='number'
                                        placeholder='0'
                                        {...field}
                                        onChange={(e) => field.onChange(e.target.value ? parseInt(e.target.value) : 0)}
                                    />
                                </FormControl>
                                <FormDescription>
                                    Меньшие числа отображаются первыми. Используйте 0 для высшего приоритета.
                                </FormDescription>
                                <FormMessage />
                            </FormItem>
                        )}
                    />

                    {/* Is Active Checkbox */}
                    <FormField
                        control={form.control}
                        name='isActive'
                        render={({ field }) => (
                            <FormItem className='flex flex-row items-start space-x-3 space-y-0'>
                                <FormControl>
                                    <Checkbox
                                        checked={field.value}
                                        onCheckedChange={field.onChange}
                                        aria-label="Активная спецификация"
                                    />
                                </FormControl>
                                <div className='space-y-1 leading-none'>
                                    <FormLabel>
                                        Активная спецификация
                                    </FormLabel>
                                    <FormDescription>
                                        Эта спецификация будет доступна для использования в товарах
                                    </FormDescription>
                                </div>
                                <FormMessage />
                            </FormItem>
                        )}
                    />

                    {/* Submit Button */}
                    <div className='flex gap-4'>
                        <Button
                            type='button'
                            variant='outline'
                            size='lg'
                            className='flex-1'
                            onClick={handleCancelForm}
                            disabled={form.formState.isSubmitting}
                        >
                            Отмена
                        </Button>
                        <Button
                            type='submit'
                            size='lg'
                            disabled={form.formState.isSubmitting}
                            className='flex-1'
                        >
                            {form.formState.isSubmitting ? 'Обновление...' : 'Обновить спецификацию'}
                        </Button>
                    </div>
                </form>
            </Form>
        </div>
    );
};

export default UpdateSpecificationForm;