import type { Metadata } from "next";
import Header from "@/components/shared/layout/header";
import { Toaster } from "@/components/ui/sonner"
import Footer from "@/components/shared/layout/footer";






export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <div className='flex flex-col bg-[#FAFAFA]'>
          <Header />
          <main className='flex-1 main-wrapper ' style={{paddingTop: '5rem'}}>{children}</main>
          <Footer />
          <Toaster />
      </div>


  );
}
