import type { Metadata } from "next";
import Header from "@/components/shared/layout/header";
import { Toaster } from "@/components/ui/sonner"






export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <div className='flex h-screen flex-col'>
          <Header />
          <main className='flex-1 wrapper'>{children}</main>
          <Toaster />
      </div>


  );
}
